### ISSUE TITLE
No version with https instead of http endpoint?

### ISSUE THREAD

**Issue by keltia** [dougsko/pastebin#1]
Hello, just tried to write a patch for moving the endpoint to https instead of http.  The patch is fine but it seems that trying to run tests does not work anymore because the 'rcov' gem is obsolete as well and does not install here with Ruby 2.4.1.

Still interested in that gem BTW?  No update since 2012…

**Comment by dougsko** [comment]
Hello,
Thanks for the heads up.  It's been one of those things that "just worked" for so long that I haven't looked at it in a while but I do want to keep it functional.  Let me update those tests and some other things that probably need updating and I'd love to check out any pull requests you might have.  Thanks!

**Comment by keltia** [comment]
According to Doug Prostko:
> Thanks for the heads up.  It's been one of those things that "just worked" for so long that I haven't looked at it in a while but I do want to keep it functional.  Let me update those tests and some other things that probably need updating and I'd love to check out any pull requests you might have.  Thanks!

Done :)
https://github.com/dougsko/pastebin/pull/2

-- 
Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- roberto@keltia.net
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/
